export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST"
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL"

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST"
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS"
export const UPDATE_NOTIFICATION_FAIL = "UPDATE_NOTIFICATION_FAIL"

export const UPDATE_ALL_NOTIFICATION_REQUEST = "UPDATE_ALL_NOTIFICATION_REQUEST"

export const GET_UNREAD_NOTIFICATION_REQUEST = "GET_UNREAD_NOTIFICATION_REQUEST"
export const GET_UNREAD_NOTIFICATION_SUCCESS = "GET_UNREAD_NOTIFICATION_SUCCESS"
export const GET_UNREAD_NOTIFICATION_FAIL = "GET_UNREAD_NOTIFICATION_FAIL"