export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_LIKED_REQUEST = "USER_LIKED_REQUEST"
export const USER_LIKED_SUCCESS = "USER_LIKED_SUCCESS"
export const USER_LIKED_FAIL = "USER_LIKED_FAIL"

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST"
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS"
export const USER_FOLLOW_FAIL = "USER_FOLLOW_FAIL"